#!/bin/bash

# smart age bin sizes
kaggle competitions submit -c h-and-m-personalized-fashion-recommendations -f ../out/age_bin_week_106_smart_threshold_10.csv.gz -m "smart age bin sizes threshold 10"
kaggle competitions submit -c h-and-m-personalized-fashion-recommendations -f ../out/age_bin_week_106_smart_threshold_30.csv.gz -m "smart age bin sizes threshold 30"
kaggle competitions submit -c h-and-m-personalized-fashion-recommendations -f ../out/age_bin_week_106_smart_threshold_50.csv.gz -m "smart age bin sizes threshold 50"
kaggle competitions submit -c h-and-m-personalized-fashion-recommendations -f ../out/age_bin_week_106_smart_threshold_70.csv.gz -m "smart age bin sizes threshold 70"
kaggle competitions submit -c h-and-m-personalized-fashion-recommendations -f ../out/age_bin_week_106_smart_threshold_90.csv.gz -m "smart age bin sizes threshold 90"
kaggle competitions submit -c h-and-m-personalized-fashion-recommendations -f ../out/age_bin_week_106_smart_threshold_110.csv.gz -m "smart age bin sizes threshold 110"
kaggle competitions submit -c h-and-m-personalized-fashion-recommendations -f ../out/age_bin_week_106_smart_threshold_130.csv.gz -m "smart age bin sizes threshold 130"
kaggle competitions submit -c h-and-m-personalized-fashion-recommendations -f ../out/age_bin_week_106_smart_threshold_150.csv.gz -m "smart age bin sizes threshold 150"
kaggle competitions submit -c h-and-m-personalized-fashion-recommendations -f ../out/age_bin_week_106_smart_threshold_170.csv.gz -m "smart age bin sizes threshold 170"
kaggle competitions submit -c h-and-m-personalized-fashion-recommendations -f ../out/age_bin_week_106_smart_threshold_190.csv.gz -m "smart age bin sizes threshold 190"

# product bin sizes
kaggle competitions submit -c h-and-m-personalized-fashion-recommendations -f ../out/age_bin_prod_week_106_bin_size_1.csv.gz -m "notebook product age bin 1"
kaggle competitions submit -c h-and-m-personalized-fashion-recommendations -f ../out/age_bin_prod_week_106_bin_size_2.csv.gz -m "notebook product age bin 2"
kaggle competitions submit -c h-and-m-personalized-fashion-recommendations -f ../out/age_bin_prod_week_106_bin_size_3.csv.gz -m "notebook product age bin 3"
kaggle competitions submit -c h-and-m-personalized-fashion-recommendations -f ../out/age_bin_prod_week_106_bin_size_4.csv.gz -m "notebook product age bin 4"
kaggle competitions submit -c h-and-m-personalized-fashion-recommendations -f ../out/age_bin_prod_week_106_bin_size_8.csv.gz -m "notebook product age bin 8"
kaggle competitions submit -c h-and-m-personalized-fashion-recommendations -f ../out/age_bin_prod_week_106_bin_size_16.csv.gz -m "notebook product age bin 16"
kaggle competitions submit -c h-and-m-personalized-fashion-recommendations -f ../out/age_bin_prod_week_106_bin_size_32.csv.gz -m "notebook product age bin 32"
kaggle competitions submit -c h-and-m-personalized-fashion-recommendations -f ../out/age_bin_prod_week_106_bin_size_64.csv.gz -m "notebook product age bin 64"

# smart bin upload
kaggle competitions submit -c h-and-m-personalized-fashion-recommendations -f ../out/age_bin_prod_week_106_smart_threshold_10.csv.gz -m "notebook smart product age bin 10"
kaggle competitions submit -c h-and-m-personalized-fashion-recommendations -f ../out/age_bin_prod_week_106_smart_threshold_30.csv.gz -m "notebook smart product age bin 30"
kaggle competitions submit -c h-and-m-personalized-fashion-recommendations -f ../out/age_bin_prod_week_106_smart_threshold_50.csv.gz -m "notebook smart product age bin 50"
kaggle competitions submit -c h-and-m-personalized-fashion-recommendations -f ../out/age_bin_prod_week_106_smart_threshold_70.csv.gz -m "notebook smart product age bin 70"
kaggle competitions submit -c h-and-m-personalized-fashion-recommendations -f ../out/age_bin_prod_week_106_smart_threshold_90.csv.gz -m "notebook smart product age bin 90"
kaggle competitions submit -c h-and-m-personalized-fashion-recommendations -f ../out/age_bin_prod_week_106_smart_threshold_110.csv.gz -m "notebook smart product age bin 110"
kaggle competitions submit -c h-and-m-personalized-fashion-recommendations -f ../out/age_bin_prod_week_106_smart_threshold_130.csv.gz -m "notebook smart product age bin 130"
kaggle competitions submit -c h-and-m-personalized-fashion-recommendations -f ../out/age_bin_prod_week_106_smart_threshold_150.csv.gz -m "notebook smart product age bin 150"
kaggle competitions submit -c h-and-m-personalized-fashion-recommendations -f ../out/age_bin_prod_week_106_smart_threshold_170.csv.gz -m "notebook smart product age bin 170"
kaggle competitions submit -c h-and-m-personalized-fashion-recommendations -f ../out/age_bin_prod_week_106_smart_threshold_190.csv.gz -m "notebook smart product age bin 190"

# naive temporal embedding
kaggle competitions submit -c h-and-m-personalized-fashion-recommendations -f ../out/embedding_week_106_nr_1_temporal.csv.gz -m "naive temporal embedding 1 week"
kaggle competitions submit -c h-and-m-personalized-fashion-recommendations -f ../out/embedding_week_106_nr_2_temporal.csv.gz -m "naive temporal embedding 2 weeks"
kaggle competitions submit -c h-and-m-personalized-fashion-recommendations -f ../out/embedding_week_106_nr_3_temporal.csv.gz -m "naive temporal embedding 3 weeks"
kaggle competitions submit -c h-and-m-personalized-fashion-recommendations -f ../out/embedding_week_106_nr_5_temporal.csv.gz -m "naive temporal embedding 5 weeks"
kaggle competitions submit -c h-and-m-personalized-fashion-recommendations -f ../out/embedding_week_106_nr_10_temporal.csv.gz -m "naive temporal embedding 10 weeks"

# improved temporal embedding
kaggle competitions submit -c h-and-m-personalized-fashion-recommendations -f ../out/embedding_week_106_nr_1_temporal_improved.csv.gz -m "improved temporal embedding 1 week"
kaggle competitions submit -c h-and-m-personalized-fashion-recommendations -f ../out/embedding_week_106_nr_2_temporal_improved.csv.gz -m "improved temporal embedding 2 weeks"
kaggle competitions submit -c h-and-m-personalized-fashion-recommendations -f ../out/embedding_week_106_nr_3_temporal_improved.csv.gz -m "improved temporal embedding 3 weeks"
kaggle competitions submit -c h-and-m-personalized-fashion-recommendations -f ../out/embedding_week_106_nr_5_temporal_improved.csv.gz -m "improved temporal embedding 5 weeks"
kaggle competitions submit -c h-and-m-personalized-fashion-recommendations -f ../out/embedding_week_106_nr_10_temporal_improved.csv.gz -m "improved temporal embedding 10 weeks"

# graph walk nr
kaggle competitions submit -c h-and-m-personalized-fashion-recommendations -f ../out/embedding_week_106_nr_5_walk_nr_5.csv.gz -m "graph walk nr 5, 5 weeks"
kaggle competitions submit -c h-and-m-personalized-fashion-recommendations -f ../out/embedding_week_106_nr_3_walk_nr_5.csv.gz -m "graph walk nr 5, 3 weeks"
kaggle competitions submit -c h-and-m-personalized-fashion-recommendations -f ../out/embedding_week_106_nr_2_walk_nr_5.csv.gz -m "graph walk nr 5, 2 weeks"
kaggle competitions submit -c h-and-m-personalized-fashion-recommendations -f ../out/embedding_week_106_nr_1_walk_nr_5.csv.gz -m "graph walk nr 5, 1 week"
kaggle competitions submit -c h-and-m-personalized-fashion-recommendations -f ../out/embedding_week_106_nr_5_walk_nr_3.csv.gz -m "graph walk nr 3, 5 weeks"
kaggle competitions submit -c h-and-m-personalized-fashion-recommendations -f ../out/embedding_week_106_nr_3_walk_nr_3.csv.gz -m "graph walk nr 3, 3 weeks"
kaggle competitions submit -c h-and-m-personalized-fashion-recommendations -f ../out/embedding_week_106_nr_2_walk_nr_3.csv.gz -m "graph walk nr 3, 2 weeks"
kaggle competitions submit -c h-and-m-personalized-fashion-recommendations -f ../out/embedding_week_106_nr_1_walk_nr_3.csv.gz -m "graph walk nr 3, 1 week"
kaggle competitions submit -c h-and-m-personalized-fashion-recommendations -f ../out/embedding_week_106_nr_5_walk_nr_2.csv.gz -m "graph walk nr 2, 5 weeks"
kaggle competitions submit -c h-and-m-personalized-fashion-recommendations -f ../out/embedding_week_106_nr_3_walk_nr_2.csv.gz -m "graph walk nr 2, 3 weeks"
kaggle competitions submit -c h-and-m-personalized-fashion-recommendations -f ../out/embedding_week_106_nr_2_walk_nr_2.csv.gz -m "graph walk nr 2, 2 weeks"
kaggle competitions submit -c h-and-m-personalized-fashion-recommendations -f ../out/embedding_week_106_nr_1_walk_nr_2.csv.gz -m "graph walk nr 2, 1 week"
kaggle competitions submit -c h-and-m-personalized-fashion-recommendations -f ../out/embedding_week_106_nr_5_walk_nr_1.csv.gz -m "graph walk nr 1, 5 weeks"
kaggle competitions submit -c h-and-m-personalized-fashion-recommendations -f ../out/embedding_week_106_nr_3_walk_nr_1.csv.gz -m "graph walk nr 1, 3 weeks"
kaggle competitions submit -c h-and-m-personalized-fashion-recommendations -f ../out/embedding_week_106_nr_2_walk_nr_1.csv.gz -m "graph walk nr 1, 2 weeks"
kaggle competitions submit -c h-and-m-personalized-fashion-recommendations -f ../out/embedding_week_106_nr_1_walk_nr_1.csv.gz -m "graph walk nr 1, 1 week"

# graph walk len
kaggle competitions submit -c h-and-m-personalized-fashion-recommendations -f ../out/embedding_week_106_nr_5_walk_len_15.csv.gz -m "graph walk len 15, 5 weeks"
kaggle competitions submit -c h-and-m-personalized-fashion-recommendations -f ../out/embedding_week_106_nr_3_walk_len_15.csv.gz -m "graph walk len 15, 3 weeks"
kaggle competitions submit -c h-and-m-personalized-fashion-recommendations -f ../out/embedding_week_106_nr_2_walk_len_15.csv.gz -m "graph walk len 15, 2 weeks"
kaggle competitions submit -c h-and-m-personalized-fashion-recommendations -f ../out/embedding_week_106_nr_1_walk_len_15.csv.gz -m "graph walk len 15, 1 week"
kaggle competitions submit -c h-and-m-personalized-fashion-recommendations -f ../out/embedding_week_106_nr_5_walk_len_10.csv.gz -m "graph walk len 10, 5 weeks"
kaggle competitions submit -c h-and-m-personalized-fashion-recommendations -f ../out/embedding_week_106_nr_3_walk_len_10.csv.gz -m "graph walk len 10, 3 weeks"
kaggle competitions submit -c h-and-m-personalized-fashion-recommendations -f ../out/embedding_week_106_nr_2_walk_len_10.csv.gz -m "graph walk len 10, 2 weeks"
kaggle competitions submit -c h-and-m-personalized-fashion-recommendations -f ../out/embedding_week_106_nr_1_walk_len_10.csv.gz -m "graph walk len 10, 1 week"
kaggle competitions submit -c h-and-m-personalized-fashion-recommendations -f ../out/embedding_week_106_nr_5_walk_len_8.csv.gz -m "graph walk len 8, 5 weeks"
kaggle competitions submit -c h-and-m-personalized-fashion-recommendations -f ../out/embedding_week_106_nr_3_walk_len_8.csv.gz -m "graph walk len 8, 3 weeks"
kaggle competitions submit -c h-and-m-personalized-fashion-recommendations -f ../out/embedding_week_106_nr_2_walk_len_8.csv.gz -m "graph walk len 8, 2 weeks"
kaggle competitions submit -c h-and-m-personalized-fashion-recommendations -f ../out/embedding_week_106_nr_1_walk_len_8.csv.gz -m "graph walk len 8, 1 week"
kaggle competitions submit -c h-and-m-personalized-fashion-recommendations -f ../out/embedding_week_106_nr_5_walk_len_5.csv.gz -m "graph walk len 5, 5 weeks"
kaggle competitions submit -c h-and-m-personalized-fashion-recommendations -f ../out/embedding_week_106_nr_3_walk_len_5.csv.gz -m "graph walk len 5, 3 weeks"
kaggle competitions submit -c h-and-m-personalized-fashion-recommendations -f ../out/embedding_week_106_nr_2_walk_len_5.csv.gz -m "graph walk len 5, 2 weeks"
kaggle competitions submit -c h-and-m-personalized-fashion-recommendations -f ../out/embedding_week_106_nr_1_walk_len_5.csv.gz -m "graph walk len 5, 1 week"
kaggle competitions submit -c h-and-m-personalized-fashion-recommendations -f ../out/embedding_week_106_nr_5_walk_len_3.csv.gz -m "graph walk len 3, 5 weeks"
kaggle competitions submit -c h-and-m-personalized-fashion-recommendations -f ../out/embedding_week_106_nr_3_walk_len_3.csv.gz -m "graph walk len 3, 3 weeks"
kaggle competitions submit -c h-and-m-personalized-fashion-recommendations -f ../out/embedding_week_106_nr_2_walk_len_3.csv.gz -m "graph walk len 3, 2 weeks"
kaggle competitions submit -c h-and-m-personalized-fashion-recommendations -f ../out/embedding_week_106_nr_1_walk_len_3.csv.gz -m "graph walk len 3, 1 week"
kaggle competitions submit -c h-and-m-personalized-fashion-recommendations -f ../out/embedding_week_106_nr_5_walk_len_2.csv.gz -m "graph walk len 2, 5 weeks"
kaggle competitions submit -c h-and-m-personalized-fashion-recommendations -f ../out/embedding_week_106_nr_3_walk_len_2.csv.gz -m "graph walk len 2, 3 weeks"
kaggle competitions submit -c h-and-m-personalized-fashion-recommendations -f ../out/embedding_week_106_nr_2_walk_len_2.csv.gz -m "graph walk len 2, 2 weeks"
kaggle competitions submit -c h-and-m-personalized-fashion-recommendations -f ../out/embedding_week_106_nr_1_walk_len_2.csv.gz -m "graph walk len 2, 1 week"
kaggle competitions submit -c h-and-m-personalized-fashion-recommendations -f ../out/embedding_week_106_nr_5_walk_len_1.csv.gz -m "graph walk len 1, 5 weeks"
kaggle competitions submit -c h-and-m-personalized-fashion-recommendations -f ../out/embedding_week_106_nr_3_walk_len_1.csv.gz -m "graph walk len 1, 3 weeks"
kaggle competitions submit -c h-and-m-personalized-fashion-recommendations -f ../out/embedding_week_106_nr_2_walk_len_1.csv.gz -m "graph walk len 1, 2 weeks"
kaggle competitions submit -c h-and-m-personalized-fashion-recommendations -f ../out/embedding_week_106_nr_1_walk_len_1.csv.gz -m "graph walk len 1, 1 week"
